import { useAppStore } from '../store/useAppStore';
import type { Workout } from '../data/workouts';

interface AIWorkoutParams {
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  rounds: number;
  roundLength: number;
  restPeriod: number;
  pace: number;
  warmup: 'None' | 'Boxing' | 'Mix';
  focus: 'Speed' | 'Power' | 'Defense' | 'Conditioning' | 'Footwork' | 'Technique';
}

export const generateAIWorkout = async (params: AIWorkoutParams): Promise<Workout> => {
  const { geminiApiKey } = useAppStore.getState();
  const apiKey = (geminiApiKey?.trim()) || (import.meta.env.VITE_GEMINI_API_KEY as string)?.trim();
  const model = 'gemini-2.5-flash';
  const apiVersion = 'v1beta';

  if (!apiKey) {
    throw new Error('Please add your Gemini API Key in the Settings page to use AI features.');
  }

  const systemInstruction = `You are a professional boxing coach creating a custom workout routine.
Output your response as a pure, raw JSON object exactly matching this schema:
{
  "title": "A catchy title for this workout",
  "punchesEst": 500, // estimated total punches for the whole workout
  "combinations": [
    "1 - 2",
    "1 - 1 - 2 - Slip Right",
    "3 - 2 - 3 - Roll Left"
  ]
}

- Use numbers for standard punches (1=Jab, 2=Cross, 3=Lead Hook, 4=Rear Hook, 5=Lead Uppercut, 6=Rear Uppercut).
- Use words for defensive/footwork moves (Slip Left, Slip Right, Roll Left, Roll Right, Pull, Catch, Step, Pivot).
- Return an array of combinations. The app will cycle through these combinations during the workout.
- Provide between 4 to 8 unique combinations in the array.
- Make the combinations appropriate for a ${params.difficulty} level boxer focusing on ${params.focus}.
- Ensure the JSON is totally raw without markdown formatting (no \`\`\`json block).`;

  let promptAddition = '';
  if (params.warmup === 'Mix') {
    promptAddition = "Since the user asked for a 'Mix' warmup, include things like 'Jumping Jacks', 'High Knees', or 'Shadowboxing' mixed into the boxing combinations.";
  } else if (params.warmup === 'None') {
    promptAddition = "The user asked for NO warmup. Go straight into intense boxing combinations.";
  }

  const prompt = `Create a ${params.difficulty} boxing workout.
Focus: ${params.focus}.
Rounds: ${params.rounds}.
Time per round: ${params.roundLength} seconds.
Rest between rounds: ${params.restPeriod} seconds.
Pace (time per combination): ${params.pace} seconds.
${promptAddition}`;

  try {
    const response = await fetch(`https://generativelanguage.googleapis.com/${apiVersion}/models/${model}:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [
          {
            role: 'user',
            parts: [{ text: systemInstruction + "\n\n" + prompt }]
          }
        ],
        generationConfig: {
          temperature: 0.7,
        }
      })
    });

    if (!response.ok) {
      const errText = await response.text().catch(() => '');
      let errDetail = errText;
      
      try {
        const errJson = JSON.parse(errText);
        if (errJson.error && errJson.error.message) {
          errDetail = errJson.error.message;
        }
      } catch (e) {
        // Not JSON, use raw text or status
      }
      
      const errMessage = `API Error: ${errDetail || response.statusText || response.status}`;
      console.error('Gemini API Error:', errMessage, errText);
      throw new Error(errMessage);
    }

    const data = await response.json();
    let textOutput = data.candidates?.[0]?.content?.parts?.[0]?.text;
    
    if (!textOutput) {
      throw new Error("No content generated by AI.");
    }

    // Extract JSON block even if AI adds extra text
    const jsonMatch = textOutput.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      textOutput = jsonMatch[0];
    } else {
      // Fallback: try cleaning standard markdown
      textOutput = textOutput.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();
    }

    const result = JSON.parse(textOutput);

    // SECURITY: Sanitize and limit AI output
    const sanitizedTitle = (result.title || 'AI Custom Workout').substring(0, 100);
    const rawCombos = Array.isArray(result.combinations) ? result.combinations : ['1 - 2'];
    
    // Limit to 30 combinations max, and each combination to 200 chars max
    const sanitizedCombos = rawCombos
      .slice(0, 30)
      .map((c: any) => String(c).substring(0, 200).replace(/[<>]/g, '')); // Basic tag removal

    // Build the final Workout object
    const aiWorkout: Workout = {
      id: 'ai-generated',
      title: sanitizedTitle,
      difficulty: params.difficulty,
      focus: params.focus === 'Conditioning' ? 'Conditioning' : params.focus,
      duration: Math.min(Math.ceil((params.rounds * params.roundLength) / 60), 120), // Cap at 2 hours
      type: 'Solo Bag',
      rounds: Math.min(params.rounds, 50), // Cap rounds
      roundLength: params.roundLength,
      restBetweenRounds: params.restPeriod,
      punchesEst: Math.min(Number(result.punchesEst) || (params.rounds * 100), 10000), // Cap punch estimate
      combinations: sanitizedCombos.length > 0 ? sanitizedCombos : ['1 - 2'],
    };

    return aiWorkout;
  } catch (err: any) {
    if (err instanceof SyntaxError) {
      throw new Error("AI returned an invalid workout format. Please try again.");
    }
    throw err;
  }
};
